name: bookmet
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_storage: ^13.0.6
  flutter_image_compress: ^2.3.0
  image_picker: ^1.1.2 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0




flutter:
  assets: 
    - assets/images/  
    - image/

  uses-material-design: true

 